<a href="https://colab.research.google.com/github/PrashantShinagare/EVA5/blob/master/Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torchvision import datasets, transforms, utils

In [11]:
m = nn.LogSoftmax()
input = torch.ones(2, 3)
print(input)
output = F.log_softmax(input, dim=1)
print(output)
output_1 = F.log_softmax(input, dim=0)
print(output_1)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[-1.0986, -1.0986, -1.0986],
        [-1.0986, -1.0986, -1.0986]])
tensor([[-0.6931, -0.6931, -0.6931],
        [-0.6931, -0.6931, -0.6931]])
